apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: uniyalapp123.azurecr.io/book_catalog:v2
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: postgresql://terraform_user:x9IsNKlX4N0PJ3IHST59SQTwmoLfvMjM@dpg-crqnfgtumphs73br3ok0-a.oregon-postgres.render.com/terraform

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: uniyalapp123.azurecr.io/inventory_management:v2
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: postgresql://terraform_user:x9IsNKlX4N0PJ3IHST59SQTwmoLfvMjM@dpg-crqnfgtumphs73br3ok0-a.oregon-postgres.render.com/terraform

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  